apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chores-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
  - host: chores-app
    http:
      paths:
      - backend:
          serviceName: chores-app
          servicePort: 80
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.213