apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chores-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: chores-app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chores-app
            port:
              number: 80
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.213
