apiVersion: v1
kind: Service
metadata:
  name: chores-ingress-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: chores-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
