name: Build & Push Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Set up Docker Buildx
      run: docker buildx create --use
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push Docker Image
      run: |
        docker buildx build \
          --file Dockerfile \
          --tag jaanuk/home_chores:${{ github.run_number }} \
          --tag jaanuk/home_chores:latest \
          --build-arg DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          --build-arg DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
          --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --push .
    - name: install ansible
      run: pip install ansible
    - name: Run Ansible playbook
      run: |
          docker run --rm -v "$(pwd):/ansible" -w /ansible \
          ansible/ansible-runner:latest ansible-playbook ansible-deploy-playbook.yml

      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      